### Crear una Marca
POST http://localhost:3000/api/brand
Content-Type: application/json

{
  "name": "Samsung",
  "logo_url": "https://ejemplo.com/samsung-logo.png"
}

### Listar todas las Marcas
GET http://localhost:3000/api/brand

### Ver una Marca específica (Reemplazá el ID)
GET http://localhost:3000/api/brand/64b5f9...

### Editar una Marca (Reemplazá el ID)
PUT http://localhost:3000/api/brand/64b5f9...
Content-Type: application/json

{
  "name": "Samsung Electronics"
}

### Borrar una Marca (Reemplazá el ID)
DELETE http://localhost:3000/api/brand/64b5f9...