### Crear un Cliente 
POST http://localhost:3000/api/customer
Content-Type: application/json

{
  "name": "Juan Pérez",
  "email": "juan.perez@email.com"
}

### Listar todos los Clientes
GET http://localhost:3000/api/customers

### Ver un Cliente específico (Reemplazá el ID)
GET http://localhost:3000/api/customer/e225721b-4657-4e7d-ab9e-a15a85b1c7c8

### Editar un Cliente (Reemplazá el ID)
PUT http://localhost:3000/api/customer/e225721b-4657-4e7d-ab9e-a15a85b1c7c8
Content-Type: application/json

{
  "name": "Juan Martín Pérez"
}

### Borrar un Cliente (Reemplazá el ID)
DELETE http://localhost:3000/api/customer/64b5f9...
